shopapp/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views



app_name = 'shopapp'


urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^home/$', views.home, name='home'),


    url(r'^signup/$', views.sign_up, name='sign_up'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),

    url(r'^profile/$', views.profile, name='profile'),

    url(r'^mycart/$', views.view_cart, name='view_cart'),
    url(r'^aboutus/$', views.about_us, name='about_us'),

    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^success/<str:args>/', views.successMsg, name='success'),

    url(r'^myfavs/$', views.view_favorites, name='view_favorites'),

    url(r'^products/$', views.view_products, name='view_products'),
    url(r'^products_guest/(?P<product_id>[0-9]+)/$', views.view_product_guest, name='view_product_guest'),



    url(r'^products/(?P<product_id>[0-9]+)/$', views.product_detail, name='product_detail'),



    url(r'^submit_review/(?P<product_id>[0-9]+)/$', views.add_review, name='add_review'),

    url(r'^mycart/delete/(?P<product_id>\d+)/$', views.delete_from_cart, name='delete_from_cart')

]

theshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopapp/', include('shopapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/models.py
from django.contrib.auth.models import Permission, User
from datetime import datetime
from django.db import models
from decimal import Decimal
from django.core import validators


# Create your models here.

class Department(models.Model):
    department_name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.department_name)

class Product(models.Model):
    brand = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    sub_title = models.CharField(max_length=400)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000)
    price = models.FloatField(null=True, blank=True, default=None)
    s_choices = (('New','New'),('Certified','Certified'),('Used','Used'),)
    status = models.CharField(max_length=10,choices=s_choices, default='New')
    photo1 = models.ImageField(upload_to='place_images', blank=True)
    photo2 = models.ImageField(upload_to='place_images', blank=True)

    def __str__(self):
        return str(self.title)


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True, null = True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review_message = models.CharField(max_length=10000)
    date_posted = models.DateField(auto_now=True)
    # date_posted = models.DateField(default=timezone.now)


    def __str__(self):
        return str(self.product)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=300)
    phone = models.CharField(max_length=150, default="")
    title = models.CharField(max_length=30, default="Title")
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return str(self.user.first_name)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True, null = True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank = True, null = True)

    def __str__(self):
        return str(self.user)

class FavoriteList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True, null = True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank = True, null = True)
    favorited = models.BooleanField(default=False)

    def __str__(self):
         return str(self.user)+ ', ' + str(self.product)


from django.db import models
from django.core import validators


class OrderDetail(models.Model):

    id = models.BigAutoField(
        primary_key=True
    )

    # You can change as a Foreign Key to the user model
    customer_email = models.EmailField(
        verbose_name='Customer Email'
    )

    product = models.ForeignKey(
        to=Product,
        verbose_name='Product',
        on_delete=models.PROTECT
    )

    amount = models.IntegerField(
        verbose_name='Amount'
    )

    stripe_payment_intent = models.CharField(
        max_length=200
    )

    # This field can be changed as status
    has_paid = models.BooleanField(
        default=False,
        verbose_name='Payment Status'
    )

    created_on = models.DateTimeField(
        auto_now_add=True
    )

    updated_on = models.DateTimeField(
        auto_now_add=True
    )

shopapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import UserProfile, Cart, FavoriteList, Review
import datetime
from django.contrib.auth.forms import UserChangeForm



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
         model = User
         fields = ['username', 'email','first_name', 'last_name']

class UserProfileForm(forms.ModelForm):

    class Meta:
         model = UserProfile
         fields = ['address','phone']

class CartListForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ['user', 'product']

class FavoriteListForm(forms.ModelForm):
    class Meta:
        model = FavoriteList
        fields = ('user', 'product', 'favorited')

class ReviewForm(forms.ModelForm):
    review_message = forms.CharField(widget=forms.Textarea(attrs={'rows': '3','cols': '25',}),)

    class Meta:
        model = Review
        fields = ['user','product', 'review_message']

shopapp/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from .models import *
from .forms import *
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
from django.http.response import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, TemplateView
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json
#Edit Profile Imports
from django.contrib.auth.forms import UserChangeForm

import stripe

stripe.api_key = "sk_test_51KkfWMKqLUf6DKofStjiqe6J8BkSF02Ggcocp90zWsk25OnlT27JVeuuKzfhizPNK1oOyWvQXRMvMeEkG8ERVVk900RXLXnfjZ"

def checkout(request):
	if request.method == 'POST':

		print('Data:', request.POST)

		amount = float(request.POST['amount'])

		customer = stripe.Customer.create(
			email=request.POST['email'],
			name=request.POST['nickname'],
			source=request.POST['stripeToken']
			)

		charge = stripe.Charge.create(
			customer=customer,
			amount=round(amount),
			currency='usd',
			description="Shop Purchase"
			)

	return render(request, 'success.html', {'amount':amount})

def successMsg(request, args):
	amount = args
	return render(request, 'success.html', {'amount':amount})


# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return render(request, 'welcome_page.html')
    else:
        user = request.user
        products = Product.objects.all()

    context = {
        "user": user,
        "products":products,
        "list":list,
    }
    return render(request, 'index.html', context)

def view_favorites(request):
    favs = FavoriteList.objects.filter(user=request.user)

    context = {
        "favs":favs
    }

    return render(request, 'favorites.html', context)

def view_products(request):
    products = Product.objects.all()

    context = {
        "products":products,
    }
    return render(request, 'index2.html', context)

def view_product_guest(request, product_id):
    product = Product.objects.get(pk = product_id)

    context = {
        "product":product,
    }
    return render(request, 'product_detail2.html', context)


def product_detail(request, product_id):
    product = Product.objects.get(pk = product_id)
    cart = Cart.objects.filter(user=request.user)
    reviews = Review.objects.filter(product_id=product_id)

    form = CartListForm(request.POST or None)
    form2 = FavoriteListForm(request.POST or None)

    list = []
    for i in cart:
        list.append(i.product.id)

    # if form.is_valid():
    #     cx = form.save(commit=False)
    #     cx.user = request.user
    #     cx.product = product
    #     cx.save()
    #
    #     return redirect('/shopapp/products/'+ product_id)
    #
    # if form2.is_valid():
    #     cx = form.save(commit=False)
    #     cx.user = request.user
    #     cx.product = product
    #     cx.favorited = True
    #     cx.save()
    #
    #     return redirect('/shopapp/products/'+ product_id)

    liked = FavoriteList.objects.filter(product = product_id)
    liked = liked.first
    # obj.delete()

    if 'btnform1' in request.POST:
        cx = form.save(commit=False)
        cx.user = request.user
        cx.product = product
        cx.save()
        return redirect('/shopapp/products/'+ product_id)

    if 'btnform2' in request.POST:
        cx = form2.save(commit=False)
        cx.user = request.user
        cx.product = product
        cx.favorited = True
        cx.save()
        return redirect('/shopapp/products/'+ product_id)

    if 'btnform3' in request.POST:
        obj = get_object_or_404(FavoriteList, product__id=product_id)
        obj.delete()
        return redirect('/shopapp/products/'+ product_id)

    if 'btnform4' in request.POST:
        obj = get_object_or_404(cart, product__id=product_id)
        obj.delete()
        return redirect('/shopapp/products/'+ product_id)


    context = {
        'product': product,
        'form': form,
        'form2': form2,
        'list':list,
        'liked':liked,
        'reviews':reviews
    }
    return render(request, 'product_detail.html', context)

def add_review(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    form = ReviewForm(request.POST or None, initial={'user': request.user, 'product': product})

    if form.is_valid():
        cx = form.save(commit=False)
        cx.save()
        return redirect('/shopapp/products/'+ product_id)

    context = {
        "form": form,
    }

    return render(request, 'add_review.html', context)

def delete_from_cart(request, product_id):
	# cart = Cart.objects.filter(user=request.user, product__id=id)

	obj = get_object_or_404(Cart, product__id=product_id)
	obj.delete()

	return redirect('/shopapp/mycart/')

def about_us(request):
	return render(request, 'about_us.html')

def view_cart(request):
    products = Product.objects.all()
    cart = Cart.objects.filter(user=request.user)

    list = []
    for i in cart:
        list.append(i.product.id)

    context = {
        "products": products,
        "cart":cart,
        "list":list,
    }
    return render(request, 'cart.html', context)


# new user register
def sign_up(request):
    user_form = UserForm(request.POST or None)
    user_form2 = UserProfileForm(request.POST or None, request.FILES or None)


    if user_form.is_valid() and user_form2.is_valid():
        user = user_form.save(commit=False)
        username = user_form.cleaned_data['username']
        password = user_form.cleaned_data['password']
        user.set_password(password)
        user_form.save()

        userprofile = user_form2.save(commit=False)
        userprofile.user = user_form.save(commit=False)
        userprofile.save()
        user = authenticate(username=username, password=password)

        if user is not None:
            return redirect('/shopapp')

    context = {
        "user_form": user_form,
        "user_form2": user_form2,
    }
    return render(request, 'signup.html', context)

def home(request):

    return render(request, 'homepage.html')

# User Login
def user_login(request):
    
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/shopapp')
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled.'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid login. Please try again.'})
    return render(request, 'login.html')

# User Logout
def user_logout(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return redirect('/shopapp')


def profile(request):
    user = request.user
    userprofile = UserProfile.objects.get(user=request.user)

    context = {
        "user": user,
        "userprofile":userprofile,
    }
    return render(request, 'profile.html', context)

shopapp/templates/about_us.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<style media="screen">
    body {
      background-image: url("https://wallpapercave.com/wp/wp2581372.jpg");
      background-position: center;
      background-repeat: repeat;
      background-size: cover;
      position: relative;
    }
    h4 {
  font-family: 'Brush Script MT', cursive;
  font-size: 40px;
}
</style>
{% endblock %}

{% block body %}

<div class="container"></div>
<br><br>
  <center><h4>Welcome to Happy Shop!</h4><br><br>
  <p>Starting as a small business in Houston, Texas year of 2022, we have big dreams. Our passion for fashion and clothing, means that we provide our customers with nothing but the highest quality of products, that are guaranteed to meet their needs and keep them satisfied!</p> 
<br>
  <p>With a motivated team, we strive to be the creative minds that bring a smile to your face. That’s why we’re always looking for innovative new ways to get the best to you.</p>
<br>
  <br><br><br><br><br><br><br><br><br><br><br>
  <h6><u>Contact Us</u></h6>
  <p>at help@happyshop.com</p></center>
</div>


{% block scripts %}
{% endblock %}

{% endblock %}

shopapp/templates/base.html
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'Logo0.png'%}">
    <title>The Shop For Everyone</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>

    {% block styles %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'shopapp:index' %}">
        <img src="{% static 'Logo.png' %}" width="40" height="40" alt="">
      </a>
      <a class="navbar-brand" href="{% url 'shopapp:home' %}">Happy Shop</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:home' %}" class="nav-link">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:index' %}" class="nav-link">Products</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:index' %}" class="nav-link">Places</a>
          </li>-->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:about_us' %}" class="nav-link">About Us</a>
          </li>
        </ul>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:view_favorites' %}" class="nav-link">My Favorites</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:view_cart' %}" class="nav-link">My Cart</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:profile' %}" class="nav-link">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:user_logout' %}" class="nav-link">Logout</a>
          </li>
        </ul>
      </div>
    </nav>

    {% block body %}
    {% endblock body %}
    {% block script %}
    {% endblock script%}
  </body>
</html>

shopapp/templates/base_visitor.html
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="icon" href="{% static 'Logo0.png'%}">

    <title>The Shop For Everyone</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% block styles %}
    {% endblock styles %}

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'shopapp:index' %}">
        <img src="{% static 'Logo.png' %}" width="40" height="40" alt="">
      </a>
      <a class="navbar-brand" href="{% url 'shopapp:index' %}">The Happy Shop</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:view_products' %}" class="nav-link">Products</a>
          </li>
          <li class="nav-item {% block login_active %}{% endblock %}">
            <a class="nav-link" href="{% url 'shopapp:user_login' %}">Login</a>
          </li>
          <li class="{% block sign_up_active %}{% endblock %}">
            <a class="nav-link" href="{% url 'shopapp:sign_up' %}">Sign Up</a>
          </li>
        </ul>
      </div>
    </nav>

    {% block body %}
    {% endblock %}
    {% block script %}
    {% endblock script%}

  </body>
</html>

shopapp/templates/favorites.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<script src="https://kit.fontawesome.com/1d3d98d1db.js" crossorigin="anonymous"></script>
<style media="screen">
  body {
      background-image: url("https://wallpapercave.com/wp/wp2581372.jpg");
      background-position: center;
      background-repeat: repeat;
      background-size: cover;
      position: relative;
    }

  .card {
      width: 100%;
      border: 1px solid gray;
  }

  .stats {
      background: white !important;
      color: #000 !important
  }

  .articles{
      font-size: 10px;
      color: #a1aab9
  }
  .followers {
      font-size: 10px;
      color: #a1aab9
  }

  .rating {
      font-size: 10px;
      color: #a1aab9
  }
  .image{
    margin: 0 auto;
  }
</style>
{% endblock %}

{% block body %}
<h1 class="mt-5 mb-5 d-flex justify-content-center">My Favorites List</h1>

<div class="container mt-2">
  <div class="row">
    {% for i in favs  %}
    <div class="col-md-12">
      <div class="card p-3 m-1">
        <a href="{% url 'shopapp:product_detail' i.product.id  %}" style="text-decoration:none">
          <div class="d-flex align-items-center">
            <div class="image" > <img src="{{ i.product.photo1.url }}" class="rounded" width="155" height="155"> </div>
              <div class="ml-2 w-100">
                  <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                      <div class="d-flex flex-column"><span><strong>{{i.product.title}}</strong></span> </div>
                  </div>
                  <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                      <div class="d-flex flex-column"> <span class="articles">Description</span> <span>{{i.product.description}}</span> </div>
                  </div>
                  <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                      <div class="d-flex flex-column"> <span class="articles">Price</span> <span>${{i.product.price}}</span> </div>
                  </div>

              </div>
          </div>
        </a>
      </div>
    </div>
    {% endfor %}
  </div>

</div>

{% block scripts %}
{% endblock %}

{% endblock %}

shopapp/templates/footer.html
{% load static %}
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://github.com/" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2022 Copyright
    </div>
    <!--/.Copyright-->

  </footer>

shopapp/templates/homepage.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
  <style media="screen">
    .bg-image {
      background-image: url("{% static 'home2.jpg' %}");
      height: 100vh;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      position: relative;
    }
    .bg-text {
      text-align: center;
      position: absolute;
      top: 40%;
      left: 50%;
      transform: translate(-50%, -50%);
      color: white;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="bg-image">
    <div class="bg-text">
      <h1 style="font-size:50px">Connecting local sellers with the world.</h1>
      <h3>Community is everything</h3>
      <a href="{% url 'shopapp:index' %}"><button class="btn btn-light">Start Shopping</button></a>

    </div>
  </div>
{% endblock %}

{% block scripts %}
{% endblock %}

shopapp/templates/profile.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<style media="screen">
  body {
      background-image: url("https://wallpapercave.com/wp/wp2581372.jpg");
      background-position: center;
      background-repeat: repeat;
      background-size: cover;
      position: relative;
    }

  .card {
      width: 60%;
      border: 1px solid rgb(214, 214, 214);
  }

  .stats {
      background: #f2f5f8 !important;
      color: #000 !important
  }

  .articles{
      font-size: 10px;
      color: #a1aab9
  }
  .followers {
      font-size: 10px;
      color: #a1aab9
  }

  .rating {
      font-size: 10px;
      color: #a1aab9
  }
  .image{
    margin: 0 auto;
  }
</style>
{% endblock %}

{% block body %}
<!-- <div class="mt-5 d-flex">
  <img src="{{ userprofile.image.url }}" class="rounded image" width="155">
</div> -->
<div class="container mt-5 d-flex justify-content-center">
    <div class="card p-3">
      <!-- <div class="image" > <img src="{{ userprofile.image.url }}" class="rounded" width="155"> </div> -->
      <img src="{{ userprofile.image.url }}" class="rounded image" width="155">

        <div class="d-flex align-items-center">

            <div class="ml-2 w-100">
                <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                    <div class="d-flex flex-column"> <span class="articles">Name</span> <span>{{user.first_name}} {{user.last_name}}</span> </div>
                </div>
                <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                    <div class="d-flex flex-column"> <span class="articles">Username</span> <span>{{user}}</span> </div>
                </div>
                <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                    <div class="d-flex flex-column"> <span class="articles">Address</span> <span>{{userprofile.address}}</span> </div>
                </div>
                <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                    <div class="d-flex flex-column"> <span class="followers">Phone</span> <span>{{userprofile.phone}}</span> </div>
                </div>
                <div class="button mt-2 d-flex flex-row align-items-center">
                  <a href="{% url 'shopapp:view_favorites' %}" class="btn btn-sm btn-outline-primary w-100">My Favorites</a>

                  <a href="{% url 'shopapp:view_cart' %}" class="btn btn-sm btn-outline-primary w-100 ml-2">My Cart</a>
                </div>
            </div>
        </div>
    </div>
</div>


  <!-- <div class="container mt-5 d-flex justify-content-center">
      <div class="card p-3">
          <div class="d-flex align-items-center">
              <div class="image"> <img src="{{ userprofile.image.url }}" class="rounded" width="155"> </div>
              <div class="ml-3 w-100">
                  <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                      <div class="d-flex flex-column"> <span class="articles">Name</span> <span>{{user.first_name}} {{user.last_name}}</span> </div>
                  </div>
                  <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                      <div class="d-flex flex-column"> <span class="articles">Username</span> <span>{{user}}</span> </div>
                  </div>
                  <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                      <div class="d-flex flex-column"> <span class="articles">Address</span> <span>{{userprofile.address}}</span> </div>
                  </div>
                  <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                      <div class="d-flex flex-column"> <span class="followers">Phone</span> <span>{{userprofile.phone}}</span> </div>
                  </div>
                  <div class="button mt-2 d-flex flex-row align-items-center"> <button class="btn btn-sm btn-outline-primary w-100">Chat</button> <button class="btn btn-sm btn-primary w-100 ml-2">Follow</button> </div>
              </div>
          </div>
      </div>
  </div> -->


{% block scripts %}
{% endblock %}

{% endblock %}

shopapp/templates/success.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="container">
  <div id="box">
    <h4>Thank you for your purchase of ${{amount}}!</h4>
    <p>Your items will be shipped soon. </p>
    <hr>
    <a class="myButton" href="{% url 'shopapp:index' %}">&#x2190;Back to homepage </a>
  </div>
</div>


{% endblock body %}

shopapp/templates/welcome_page.html
{% extends 'base_visitor.html' %}

{% load static %}

{% block styles %}
  <style media="screen">
    .bg-image {
      background-image: url("{% static 'home2.jpg' %}");
      height: 100vh;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      position: relative;
    }
    .bg-text {
      text-align: center;
      position: absolute;
      top: 40%;
      left: 50%;
      transform: translate(-50%, -50%);
      color: white;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="bg-image">
    <div class="bg-text">
      <h1 style="font-size:50px">Connecting local sellers with the world.</h1>
      <h3>Community is everything</h3>
      <a href="{% url 'shopapp:sign_up' %}"><button class="btn btn-light">Start Shopping</button></a>

    </div>
  </div>
{% endblock %}

{% block scripts %}
{% endblock %}